# Node.js 기반 이미지 사용
FROM node:22

# 작업 디렉토리 설정
WORKDIR /CCTV_WEATHER_PROJECT_FN

# 의존성 파일 복사 및 설치
COPY package*.json ./
RUN npm install

# 앱 소스 복사
COPY . .

# 앱 실행 포트 노출
EXPOSE 3000

# React 개발 서버 실행
#CMD ["npm", "start"]
CMD ["/bin/bash"]
